name: release tests
on: [push, pull_request]

jobs:
  install_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]
        skfem-version: [2.5.0, 3.1.0, 3.2.0]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install scikit-fem ${{ matrix.skfem-version }}
      run: |
        python -m pip install --upgrade pip
        pip install scikit-fem==${{ matrix.skfem-version }}
    - name: Clone tests
      run: |
        git clone --depth 1 --branch ${{ matrix.skfem-version }} https://github.com/kinnala/scikit-fem.git
        rm -r scikit-fem/skfem
    - name: Install test dependencies
      run: |
        pip install -r scikit-fem/requirements.txt
    - name: Run tests
      run: |
        cd scikit-fem && pytest -k 'not TestEx32 and not TestEx28 and not TestEx09'
